### ISSUE TITLE
No linux-ppc64le packages for 6.28.0

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/root-feedstock#199]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There are no uploaded packages for the 6.28.0 release:

https://anaconda.org/conda-forge/root_base/files?version=6.28.0

As of 36eb6fd1470708a607f06c6b0015e82195c5d18d the linux-arch builds run on Travis, but all timeout, see https://app.travis-ci.com/github/conda-forge/root-feedstock/builds/261630195.

Can packages for these archs be uploaded manually, or should downstream just stop attempting to build for linux-arch (for a while)?

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by chrisburr** [comment]
This issue is somewhat blocked by ROOT no longer working with QEMU so the pseudo-cross-compilation trick no longer works for CI (seems to be due to the LLVM update, I owe ROOT a reproducer so they can investigate and hopefully fix it).

I have native hardware I can use which is okay for `linux-aarch64` but for `linux-ppc64le` it's a bit painful as it's so slow. If you have an actual use case for `ppc64le` I can try to make it happen else I'd suggest skipping it for a while.
